### ISSUE TITLE
New indigo release

### ISSUE THREAD

**Issue by jonbinney** [OSUrobotics/rosh_core#6]
Could you do another release into indigo? Without https://github.com/OSUrobotics/rosh_core/commit/8e013f666e6258c5b52fdcdfb6d1b0cfe239695e the debs don't seem to be usable (fail to find impl when you "import rosh")

**Comment by dlaz** [comment]
I made that change because without rosh.impl in packages, rosh.impl couldn't be imported in install space. Not sure what the right solution is - posted to ROS Answers: http://answers.ros.org/question/187867/python-inconsistency-between-deb-and-install-space/

Also good motivation to get the tests working so we can avoid non-functional debs in the future.

Note: also applies to hydro.

**Comment by jonbinney** [comment]
So before https://github.com/OSUrobotics/rosh_core/commit/8e013f666e6258c5b52fdcdfb6d1b0cfe239695e rosh didn't work in install space. After https://github.com/OSUrobotics/rosh_core/commit/8e013f666e6258c5b52fdcdfb6d1b0cfe239695e it works in devel and install space, but debs haven't been created, right? I don't see any release tags after that commit.

**Comment by dlaz** [comment]
Oh, I thought I had done a release since that commit, but I guess not. Then the fix is just doing a new release with 8e013f6, yes?

**Comment by jonbinney** [comment]
Yeah, I think that should take care of it.

**Comment by dlaz** [comment]
Released rosh_core 1.0.6 at cd392fd60f5f763f7c1ceb3912787468ada32599 for hydro and indigo.

**Comment by jonbinney** [comment]
Thanks @dlaz

**Comment by jonbinney** [comment]
Just installed version 1.0.6 from shadow-fixed; can confirm that it works now.
